name: Arch PKGBUILD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - uses: actions/checkout@v2
    - name: get PKGBUILD
      run: |
       pacman -Syu --noconfirm
       pacman -Sy --noconfirm git opendoas fakeroot binutils lua sdl2 sdl2_image sdl2_ttf sdl2_mixer autoconf make gcc cmake which pkgconf glib2 glu
       useradd -m -G wheel -s /bin/bash tester
       echo permit nopass :wheel > /etc/doas.conf
       echo permit nopass root as tester >> /etc/doas.conf
       ln -s /bin/doas /bin/sudo
       echo '#!/bin/sh' > ./all.sh
       echo export LANG=en_US.UTF-8 >> ./all.sh
       echo export LC_CTYPE=en_US.UTF-8 >> ./all.sh
       echo export LC_ALL=en_US.UTF-8 >> ./all.sh
       echo cd >> ./all.sh
       echo git clone https://aur.archlinux.org/yirl-git.git/ >> ./all.sh
       echo cd yirl-git >> ./all.sh
       echo makepkg >> ./all.sh
       chmod +x ./all.sh
       cat all.sh
       sudo -u tester ./all.sh

        
