name: Arch PKGBUILD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - uses: actions/checkout@v2
    - name: get PKGBUILD
      run: |
       pacman -Sy --noconfirm git opendoas
       useradd -m -G wheel -s /bin/bash tester
       echo permit persist nopass :wheel > /etc/doas.conf
       ln -s /bin/doas /bin/sudo
       su tester
       git clone https://aur.archlinux.org/yirl-git.git/
       cd yirl-git
       makepkg -si

        
