name: Arch PKGBUILD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - uses: actions/checkout@v2
    - name: get PKGBUILD
      run: |
       pacman -Sy --noconfirm git
       git clone https://aur.archlinux.org/yirl-git.git/
    - name: build-arch-package
      uses: FFY00/build-arch-package@v1
      with:
        PKGBUILD: yirl-git/PKGBUILD
        
