name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get PKGBUILD
      run: https://aur.archlinux.org/yirl-git.git/
    - name: build-arch-package
      uses: FFY00/build-arch-package@v1
      with:
        PKGBUILD: yirl-git/PKGBUILD
        
