name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v8.0.0
    - uses: snickerbockers/submodules-init@v4
    - name: setup-dependancies
      run: |
        sudo apt-get install -y sdl2-image sdl2-mixer sdl2-ttf sdl2
        cd tinycc
        ./configure --extra-cflags=-fPIC
        make -j$(nproc)
        cd ..
        cd SDL_mixer
        ./autogen.sh
        ./configure CFLAGS="-fPIC"
        make -j$(nproc)
        cd ..
    - name: configure
      run: ./configure
    - name: make
      run: |
        make quickjs-2020-03-16
        make

