name: Docker Build Push

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build  -t yirl-build ./docker
        docker run -v $PWD:/yirl yirl-build scl enable devtoolset-9 "/yirl/docker/make.sh https://github.com/cosmo-ray/yirl.git"
        chown $(whoami) -R ./docker-package/
        ./docker-package/yirl-loader.sh -h
        mv docker-package/ yirl/
        ls -l
        tar cvfz  yirl.tar.gz ./yirl/
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            yirl.tar.gz
