name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - name: setup-dependancies
      run: |
        sudo apt-get install -y libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-dev lua5.3-dev libjson-c-dev
        cd tinycc
        ./configure --extra-cflags=-fPIC
        make -j$(nproc)
        cd ..
        cd SDL_mixer
        ./autogen.sh
        ./configure CFLAGS="-fPIC"
        make -j$(nproc)
        cd ..
    - name: configure
      run: ./configure -t ubuntu
    - name: make
      run: |
        make sdl-gpu-build
        make quickjs-2020-03-16
        make

