name: Generate mingw binaries on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
   
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          gcc
          base-devel
          zip
          mingw-w64-x86_64-msmpi
          mingw-w64-x86_64-perl
        pacboy:
          SDL2_mixer
          SDL2_image
          SDL2_ttf
          freeglut
          mesa
          cmake
          glew
          gcc
          dlfcn
          lua
          autotools
          json-c
    
    - shell: msys2 {0}
      run: |
        git submodule update --init
        ./configure -t mingw-64
        cd tinycc
        ./configure --enable-static
        make -j$(nproc)
        cd ..
        make quickjs-2020-03-16
        make yirl-loader.exe
        ./package-maker.sh ./yirl-loader.exe tmp/
        rm -f tmp/shcore.dll
        mv tmp/* .
        rm -rvf tmp core tests .git* Makefile check.sh configure* *.sh sdl-gpu sdl-gpu-build SDL_mixer tinycc/tests/ quickjs-2020-03-16/ 
        zip -r yirl.zip .
        
    - uses: "actions/upload-artifact@v4"
      with:
          name: build
          path: yirl.zip
