name: Generate mingw binaries on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
   
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          git
          gcc
          base-devel
          zip
        pacboy:
          SDL2_mixer
          SDL2_image
          SDL2_ttf
          freeglut
          mesa
          cmake
          glew
          gcc
          msmpi
          dlfcn
          lua
          autotools
          json-c
    
    - shell: msys2 {0}
      run: |
        git submodule update --init
        ./configure -t mingw-64
        cd tinycc
        ./configure --enable-static
        make -j$(nproc)
        cd ..
        cd SDL_mixer
        ./autogen.sh
        ./configure
        make -j$(nproc)
        cd ..
        #MinGW Makefiles
        cmake -B ./sdl-gpu-build ./sdl-gpu/ -G "MSYS Makefiles"
        make /d/a/yirl/yirl/sdl-gpu-build/SDL_gpu-MINGW/lib/libSDL2_gpu_s.a
        make quickjs-2020-03-16
        make yirl-loader
        ./package-maker.sh ./yirl-loader.exe tmp/
        rm -f tmp/shcore.dll
        mv tmp/* .
        rm -rvf tmp core tests .git* Makefile check.sh configure* *.sh sdl-gpu sdl-gpu-build SDL_mixer tinycc/tests/ quickjs-2020-03-16/ 
        zip -r yirl.zip .
        
    - uses: "actions/upload-artifact@v2"
      with:
          name: build
          path: yirl.zip
